In [2]:
%pwd

'/home/sarath_kumar/DS-Intern-Assignment-Sarath_Kumar-1/notebooks'

In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [3]:
# os.chdir("../")
# %pwd

'/home/sarath_kumar/DS-Intern-Assignment-Sarath_Kumar-1'

In [4]:
df = pd.read_csv("data/data.csv")
df.head()

,timestamp,equipment_energy_consumption,lighting_energy,zone1_temperature,zone1_humidity,zone2_temperature,zone2_humidity,zone3_temperature,zone3_humidity,zone4_temperature,...,zone9_temperature,zone9_humidity,outdoor_temperature,atmospheric_pressure,outdoor_humidity,wind_speed,visibility_index,dew_point,random_variable1,random_variable2
0,2016-01-11 17:00:00,60.0,-77.78778596503064,33.74660933896648,47.59666666666671,19.2,44.79,19.79,,19.0,...,17.0333333333333,45.53,6.6,733.5,92.0,7.0,63.0,5.3,13.275433157104999,13.275433157104999
1,2016-01-11 17:10:00,60.0,30.0,19.89,46.69333333333329,19.2,44.7225,19.79,44.79,19.0,...,17.0666666666667,45.56,6.48333333333333,733.6,92.0,6.66666666666667,59.16666666666669,5.2,18.606194981839508,18.606194981839508
2,2016-01-11 17:20:00,50.0,30.0,19.89,46.3,19.2,44.6266666666667,19.79,44.933333333333294,35.921143685986486,...,17.0,45.5,6.36666666666667,733.7,92.0,6.3333333333333295,55.33333333333329,5.1,28.64266816759482,28.64266816759482
3,2016-01-11 17:30:00,50.0,40.0,33.74660933896648,46.0666666666667,19.2,44.59,19.79,45.0,,...,17.0,45.4,6.25,733.7999999999998,92.0,6.0,51.5,37.67371557939622,45.410389499738805,45.410389499738805
4,2016-01-11 17:40:00,60.0,40.0,19.89,46.33333333333329,19.2,44.53,19.79,45.0,18.89,...,4.476510916975878,45.4,6.133333333333329,733.9,92.0,5.66666666666667,47.66666666666669,4.9,10.084096551872788,10.084096551872788

In [5]:
print("Data Shape:", df.shape)
print("\nSummary Statistics:\n", df.describe())

# Data Types
print("\nData Types:\n", df.dtypes)

# Missing Values
missing_values = df.isnull().sum()
missing_percentage = (missing_values / len(df)) * 100
print("\nMissing Values:\n", missing_values)
print("\nMissing Value Percentage:\n", missing_percentage)

Data Shape: (16857, 29)

Summary Statistics:
         timestamp             equipment_energy_consumption  \
count                 16857                          16857
unique                16769                            132
top     2016-02-13 00:00:00   50.0
freq                      2                           3400

         lighting_energy      zone1_temperature    zone1_humidity       \
count                 16857                16857                 16857
unique                   22                  435                  2174
top      0.0
freq                  11687                  854                   789

         zone2_temperature    zone2_humidity        zone3_temperature   \
count                 16857                 16857                16857
unique                  840                  2167                  863
top
freq                    835                   867                  802

         zone3_humidity        zone4_temperature   ...   zone9_temperature   \
count                  16857                16857  ...                16857
unique                  1987                  924  ...                  515
top                                                ...
freq                     878                  816  ...                  773

         zone9_humidity        outdoor_temperature     atmospheric_pressure  \
count                  16857                   16857                  16857
unique                  2388                    1435                   2107
top
freq                     888                     806                    842

         outdoor_humidity      wind_speed           visibility_index    \
count                  16857                16857                16857
unique                   608                  169                  377
top                            1.0                  40.0
freq                     799                 1571                 5563

         dew_point               random_variable1     random_variable2
count                    16857                 16857             16857
unique                    1146                 15592             15620
top
freq                       826                   826               824

[4 rows x 29 columns]

Data Types:
 timestamp                        object
 equipment_energy_consumption    object
 lighting_energy                 object
 zone1_temperature               object
 zone1_humidity                  object
 zone2_temperature               object
 zone2_humidity                  object
 zone3_temperature               object
 zone3_humidity                  object
 zone4_temperature               object
 zone4_humidity                  object
 zone5_temperature               object
 zone5_humidity                  object
 zone6_temperature               object
 zone6_humidity                  object
 zone7_temperature               object
 zone7_humidity                  object
 zone8_temperature               object
 zone8_humidity                  object
 zone9_temperature               object
 zone9_humidity                  object
 outdoor_temperature             object
 atmospheric_pressure            object
 outdoor_humidity                object
 wind_speed                      object
 visibility_index                object
 dew_point                       object
 random_variable1                object
 random_variable2                object
dtype: object

Missing Values:
 timestamp                        0
 equipment_energy_consumption    0
 lighting_energy                 0
 zone1_temperature               0
 zone1_humidity                  0
 zone2_temperature               0
 zone2_humidity                  0
 zone3_temperature               0
 zone3_humidity                  0
 zone4_temperature               0
 zone4_humidity                  0
 zone5_temperature               0
 zone5_humidity                  0
 zone6_temperature               0
 zone6_humidity                  0
 zone7_temperature               0
 zone7_humidity                  0
 zone8_temperature               0
 zone8_humidity                  0
 zone9_temperature               0
 zone9_humidity                  0
 outdoor_temperature             0
 atmospheric_pressure            0
 outdoor_humidity                0
 wind_speed                      0
 visibility_index                0
 dew_point                       0
 random_variable1                0
 random_variable2                0
dtype: int64

Missing Value Percentage:
 timestamp                        0.0
 equipment_energy_consumption    0.0
 lighting_energy                 0.0
 zone1_temperature               0.0
 zone1_humidity                  0.0
 zone2_temperature               0.0
 zone2_humidity                  0.0
 zone3_temperature               0.0
 zone3_humidity                  0.0
 zone4_temperature               0.0
 zone4_humidity                  0.0
 zone5_temperature               0.0
 zone5_humidity                  0.0
 zone6_temperature               0.0
 zone6_humidity                  0.0
 zone7_temperature               0.0
 zone7_humidity                  0.0
 zone8_temperature               0.0
 zone8_humidity                  0.0
 zone9_temperature               0.0
 zone9_humidity                  0.0
 outdoor_temperature             0.0
 atmospheric_pressure            0.0
 outdoor_humidity                0.0
 wind_speed                      0.0
 visibility_index                0.0
 dew_point                       0.0
 random_variable1                0.0
 random_variable2                0.0
dtype: float64